### ISSUE TITLE
Miscompilation involving tuples and options

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#523] opened 2024-05-07 11:05 UTC
This is as far as I could reduce it:

```
type bits2 = (bits(32), option(bits(32)))

function foo() -> result(bits2, unit) = {
  let tr1 = {
    let tr1 : bits(32) = 0x12345678;
    Some(tr1)
  };
  Ok(0x12345678, tr1)
}
```

It compiles to C fine, but when compiling the C I get this warning-that-should-be-an-error

```
model.c: In function ‘zfoo’:
model.c:319:18: warning: passing argument 1 of ‘zSomezIbzK’ from incompatible pointer type [-Wincompatible-pointer-types]
       zSomezIbzK(&zuz30, zgsz36);
                  ^~~~~~
model.c:85:45: note: expected ‘struct zoptionzIbzK *’ but argument is of type ‘uint64_t *’ {aka ‘long unsigned int *’}
 static void zSomezIbzK(struct zoptionzIbzK *rop, lbits op)
                        ~~~~~~~~~~~~~~~~~~~~~^~~
```

Actually in my non-reduced code it *is* an error, but maybe that's because I'm compiling the code as C++ and I guess C++ is more strict about these mistakes?

Both of these work fine:

```
function foo() -> result(bits2, unit) = {
  let tr1 = {
    Some(0x12345678)
  };
  Ok(0x12345678, tr1)
}

function foo() -> result(bits2, unit) = {
  Ok(0x12345678, {
    let tr1 : bits(32) = 0x12345678;
    Some(tr1)
  })
}
```

**Comment by Alasdair** [comment] 2024-05-07 14:18
``` 
let tr1 = {
    let tr1 : bits(32) = 0x12345678;
    Some(tr1)
  };
```
The issue is I didn't consider the inner tr1 to be shadowing the outer tr1, as in Sail the outer tr1 isn't in scope within that block. However in C, it does need to be considered as shadowing because we use a reference inside the block to assign the Some result to the (outer) tr1 variable.

Should be fixed by: https://github.com/rems-project/sail/pull/525

**Comment by Timmmm** [comment] 2024-05-07 15:03
Ahhh, also means there's an easy workaround. Thanks!

**Closed as completed** 2024-05-08 14:26 UTC
