### ISSUE TITLE
../examples/prelude.sail not found when building asciidoc

### ISSUE THREAD

**Issue by shp4rk** [rems-project/sail#481] opened 2024-03-23 12:02 UTC
I ran `opam pin add sail` to use `sail` built from `sail2` branch (`361f598`).

When I tried running `make -C doc/ascii`, and I got this error:

```
$ make -C ./doc/asciidoc
make: Entering directory '/home/shpark/projects/rems-project/sail/doc/asciidoc'
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/riscv_duopod.sail -doc_embed plain -doc_bundle riscv_duopod.json ../examples/riscv_duopod.sail 2> sail_doc/riscv_duopod.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/pattern_matching.sail -doc_embed plain -doc_bundle pattern_matching.json ../examples/pattern_matching.sail 2> sail_doc/pattern_matching.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/my_replicate_bits.sail -doc_embed plain -doc_bundle my_replicate_bits.json ../examples/my_replicate_bits.sail 2> sail_doc/my_replicate_bits.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/bitfield.sail -doc_embed plain -doc_bundle bitfield.json ../examples/bitfield.sail 2> sail_doc/bitfield.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/exn.sail -doc_embed plain -doc_bundle exn.json ../examples/exn.sail 2> sail_doc/exn.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/mapping.sail -doc_embed plain -doc_bundle mapping.json ../examples/mapping.sail 2> sail_doc/mapping.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/scattered.sail -doc_embed plain -doc_bundle scattered.json ../examples/scattered.sail 2> sail_doc/scattered.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/tuples.sail -doc_embed plain -doc_bundle tuples.json ../examples/tuples.sail 2> sail_doc/tuples.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/string.sail -doc_embed plain -doc_bundle string.json ../examples/string.sail 2> sail_doc/string.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/function_pat.sail -doc_embed plain -doc_bundle function_pat.json ../examples/function_pat.sail 2> sail_doc/function_pat.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/let_var.sail -doc_embed plain -doc_bundle let_var.json ../examples/let_var.sail 2> sail_doc/let_var.warning
mkdir -p sail_doc
sail -no_color -doc -doc_file ../examples/list.sail -doc_embed plain -doc_bundle list.json ../examples/list.sail 2> sail_doc/list.warning
mkdir -p module_sail_doc
sail -doc  -doc_embed plain -doc_bundle simple_mod.json -o module_sail_doc ../examples/simple_mod.sail_project
mkdir -p module_sail_doc
sail -no_color ../examples/simple_mod_err.sail_project 2> module_sail_doc/simple_mod_err.error
make: [Makefile:46: module_sail_doc/simple_mod_err.error] Error 1 (ignored)
mkdir -p module_sail_doc
sail ../examples/cond.sail_project -list_files 1>/dev/null
Error:
../examples/prelude.sail: No such file or directory
make: *** [Makefile:50: module_sail_doc/cond.sail_project] Error 1
make: Leaving directory '/home/shpark/projects/rems-project/sail/doc/asciidoc'
```

Is `make -C ./doc/asciidoc` supposed to run out-of-box, or am I missing something?

**Comment by rod7760** [comment] 2024-03-29 17:43
I had the same issue.

**Comment by Alasdair** [comment] 2024-03-29 19:28
Should be fixed by https://github.com/rems-project/sail/pull/485

Will require updating Sail to that commit once the tests run and I merge it, the error was caused by a change in the `--list-files` flag being used by the documentation Makefile to check that files being pulled into the documentation were at least syntactically valid. You could also just delete that line from the Makefile as it's just doing a check and doesn't affect the output.

**Comment by Alasdair** [comment] 2024-03-29 19:58
Will close this issue for now, please feel free to make a new one if you run into any subsequent issues. Between the ruby stuff for asciidoctor and using latex+tikz for figures I suspect it's kinda difficult to get working. I did add a Dockerfile that might be useful as it shows all the needed dependencies.

**Closed as completed by Alasdair** 2024-03-29 19:58 UTC
