### ISSUE TITLE
sail2 confused by type synonym in union constructor when compiling to ocaml

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#2] opened 2018-02-23 16:03 UTC
```
type tuparg = (int, int)

union Bar = {
      X : tuparg
}
```
Gives:
```
Type error at no location information available

Function X not applied to enough arguments
```

**Comment by Alasdair** [comment] 2018-02-23 16:58
The problem is that in some contexts "(int, int)" can have two meanings - usually it means a tuple, but in some contexts such as function types it means multiple arguments, so `(int, int) -> int` is a function that takes two ints and returns an int - similarly in a union type the type `X : (int, int)` is creating a constructor X with two arguments, no a constructor that takes a tuple.

However, in the AST the function type is something like `typ * typ * effects`, with the multiple arguments in a `Typ_tup` constructor, rather than `typ list -> typ -> effects`, which is how it should actually work. The upside (or downside, depending on perspective) is that type synonyms for tuples can be used in places where a type list should appear and it often just works...

In this case however, Sail will try to generated a undefined_Bar function when compiling to ocaml to handle expressions like let x : Bar = undefined. This happends before type-synonym expansion (which should be fine!) but it means the leaks in this abstraction become apparent.

The real fix is refactoring the AST such that we have `Typ_fn of typ list * typ * ty` and similarly for type union constructors, and generally be more strict about mixing of tuples and things that look like tuples. This mixing also causes issues with wildcard patterns, i.e. we probably shouldn't allow:
```
val f : (int, int) -> int
function f _ = 0 // should really be function f (_, _) = 0
```
but we do for similar reasons.

**Comment by rmn30** [comment] 2018-09-26 15:11
I think this is the same problem but was recently thrown by this fairly minimal example that gives the "no location information available" error:
`
val foo : int -> unit
function foo () = ()
`
Note that the code is incorrect because of the missing argument to foo in function definition but the error message is not helpful...

**Comment by Alasdair** [comment] 2018-09-27 11:08
Commit 645a5d90df9fc8f89ab9d6868c1a51f7429a890d should fix that specific error message, but I'm not sure we should mark this closed as there are still some underlying issues that need to be addressed.

**Closed** 2024-02-21 18:19 UTC
Labels: bug, refactor
